// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8L__qQIWVCHEWqf3gTY7GwfZ20We-acs',
    appId: '1:164294391147:web:379ad4be943c340b53882e',
    messagingSenderId: '164294391147',
    projectId: 'paani-ccae7',
    authDomain: 'paani-ccae7.firebaseapp.com',
    storageBucket: 'paani-ccae7.appspot.com',
    measurementId: 'G-Y0LR5W5P4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2EA5qirFdnNS9iNEuh8o8NukJmdLx1qQ',
    appId: '1:164294391147:android:220c3712d8f42c2f53882e',
    messagingSenderId: '164294391147',
    projectId: 'paani-ccae7',
    storageBucket: 'paani-ccae7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX9vVVK7Y4dkgtCTWsr5494fl1z_5Gz8Y',
    appId: '1:164294391147:ios:fdb6feea811a112a53882e',
    messagingSenderId: '164294391147',
    projectId: 'paani-ccae7',
    storageBucket: 'paani-ccae7.appspot.com',
    iosClientId: '164294391147-fhmkjbrc60b45ogu8ekubtfcrhu7qdq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.paani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX9vVVK7Y4dkgtCTWsr5494fl1z_5Gz8Y',
    appId: '1:164294391147:ios:fdb6feea811a112a53882e',
    messagingSenderId: '164294391147',
    projectId: 'paani-ccae7',
    storageBucket: 'paani-ccae7.appspot.com',
    iosClientId: '164294391147-fhmkjbrc60b45ogu8ekubtfcrhu7qdq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.paani',
  );
}
